version: "2.30"

services:
  test_system:
    build: 
      context: ./backend
    container_name: test_system_ci
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/media:/app/media
    env_file:
      - ./backend/.env.ci
    depends_on:
      - db
    networks:
      - app-network

  mcl_ui:
    build:
      context: ./frontend/mcl_ui
    container_name: mcl_ui_ci
    env_file:
      - ./frontend/mcl_ui/.env.ci
    ports:
      - "8080:80"
    depends_on:
      - test_system
    networks:
      - app-network
  
  db:
    image: postgres:latest
    container_name: media_co_lab_db_ci
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: test_db
    networks:
      - app-network
    volumes:
      - db_data_ci:/var/lib/postgresql/data

networks:
  app-network:
    driver: bridge

volumes:
  db_data_ci:
