version: "2.3"

services:
  test_system:
    build: 
      context: ./backend
    container_name: test_system
    volumes:
      - ./backend:/app
      - ./backend/media:/app/media
    env_file:
      - ./backend/.env.ci
    depends_on:
      - db
    networks:
      - app-network

  mcl_ui:
    build:
      context: ./frontend/mcl_ui
    container_name: mcl_ui
    env_file:
      - ./frontend/mcl_ui/.env.ci
    depends_on:
      - test_system
    networks:
      - app-network
  
  db:
    image: postgres:latest
    container_name: media_co_lab_db
    env_file:
      - ./backend/.env.ci
    networks:
      - app-network
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      retries: 5

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
