# Generated by Django 4.2.5 on 2024-02-08 04:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('title', models.CharField(max_length=255)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=255)),
                ('preset_type', models.CharField(choices=[('sandstone', 'Sandstone'), ('cemented_sand', 'Cemented Sand'), ('siltstone', 'Siltstone'), ('shale_sand', 'Shale Sand'), ('sandy_shale', 'Sandy Shale'), ('shale', 'Shale'), ('organic_rich_mudstone', 'Organic Rich Mudstone'), ('cemented_shale', 'Cemented Shale'), ('marl', 'Marl'), ('limestone', 'Limestone'), ('dolomite', 'Dolomite'), ('halite', 'Halite'), ('anhydrite', 'Anhydrite'), ('igneous', 'Igneous'), ('tuff', 'Tuff'), ('coal_lignite', 'Coal Lignite'), ('conglomerate_breccia', 'Conglomerate Breccia'), ('bad_hole', 'Bad Hole'), ('custom', 'Custom')], max_length=255)),
                ('custom_preset_type', models.CharField(blank=True, max_length=255, null=True)),
                ('top_depth', models.FloatField()),
                ('bottom_depth', models.FloatField()),
                ('layer_width', models.FloatField(blank=True, null=True)),
                ('well_name', models.CharField(max_length=255)),
            ],
        ),
    ]
