name: CI Pipeline MCL

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

jobs:
  lint-test-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build and Start Services
        run: docker compose -f docker-compose.ci.yml up --build -d

      - name: Wait for Database to Be Ready
        run: |
          until docker exec media_co_lab_db pg_isready -U postgres; do
            echo "Waiting for PostgreSQL to be ready..."
            sleep 3
          done

      - name: Run Linter
        run: |
          pip install black
          black --check ./backend

      - name: Skip tests
        run: echo "Skipping tests since none are defined"

      - name: Shutdown Services
        if: always()
        run: docker compose -f docker-compose.ci.yml down
