name: CI Pipeline

# Define the triggers for this workflow
on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

jobs:
  lint-test-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Copy CI Environment Files
        run: |
          cp ./backend/.env.ci ./backend/.env
          cp ./frontend/mcl_ui/.env.ci ./frontend/mcl_ui/.env

      - name: Set Environment Variables from Secrets
        run: |
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> ./backend/.env
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> ./backend/.env

      - name: Build and Start Services
        run: docker-compose -f docker-compose.yml up --build -d

      - name: Wait for Database to Be Ready
        run: |
          until docker exec media_co_lab_db pg_isready -U postgres; do
            echo "Waiting for PostgreSQL to be ready..."
            sleep 3
          done

      - name: Skip tests
        run: echo "Skipping tests since none are defined"

      - name: Shutdown Services
        run: docker-compose -f docker-compose.yml down
